# Generated by Django 5.2.7 on 2025-10-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], default='M', max_length=1),
        ),
    ]
